### ISSUE TITLE
Server crash loop on processing Scary and Spooky Pristine Matter in Loot Fabricator.

### ISSUE THREAD

**Issue by frikinjay** [NathanPB/DeepMobLearning-Refabricated#77] opened 2022-01-09 11:59 UTC
As said in the title. Right when the matter is about to be processed the server goes into a crash loop.
Using 0.5.0 beta 2

Server logs :
```
[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException
```
Crash Report :
```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:670)

-- Block entity being ticked --
Details:
	Name: dml-refabricated:loot_fabricator // dev.nathanpb.dml.blockEntity.BlockEntityLootFabricator
	Block: Block{dml-refabricated:loot_fabricator}[facing=north]
	Block location: World: (1803,68,-2562), Section: (at 11,4,14 in 112,4,-161; chunk contains blocks 1792,-64,-2576 to 1807,319,-2561), Region: (3,-6; contains chunks 96,-192 to 127,-161, blocks 1536,-64,-3072 to 2047,319,-2561)
	Block: Block{dml-refabricated:loot_fabricator}[facing=north]
	Block location: World: (1803,68,-2562), Section: (at 11,4,14 in 112,4,-161; chunk contains blocks 1792,-64,-2576 to 1807,319,-2561), Region: (3,-6; contains chunks 96,-192 to 127,-161, blocks 1536,-64,-3072 to 2047,319,-2561)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:670)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 2 total; [class_3222['frikinjay'/158666, l='ServerLevel[world]', x=963.62, y=94.00, z=-2876.86], class_3222['Mr_Lego'/176690, l='ServerLevel[world]', x=1802.70, y=68.00, z=-2561.93]]
	Chunk stats: 4896
	Level dimension: minecraft:overworld
	Level spawn location: World: (1751,151,-2550), Section: (at 7,7,10 in 109,9,-160; chunk contains blocks 1744,-64,-2560 to 1759,319,-2545), Region: (3,-5; contains chunks 96,-160 to 127,-129, blocks 1536,-64,-2560 to 2047,319,-2049)
	Level time: 13433117 game time, 14217614 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 22380 (now: false), thunder time: 48338 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
```
Mod List :
```
Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		advancednetherite: Advanced Netherite 1.3.1-1.18.1
		adventurez: AdventureZ 1.4.7
		ae2: Applied Energistics 2 10.0.0-beta.4
		ae2things: AE2Things 1.0.0-beta.3
		ae2wtlib: AE2WTLib 10.0.0-beta.4
		agape_space: Space Dimensions 0.4.6
		akashictomeoftools: Akashic Tome Of Tools Fabric 1.2
		allarmor: Oops! All Armor 1.1.1
		alloy_forgery: Alloy Forgery 2.0.8+1.18
		alternatecurrent: Alternate Current 1.1.0
		amplified_nether: Amplified Nether for Fabric 1.0.1
		annotateddi: Annotated DI 2.0.4+1.18
		antishulkerdupe: Antishulkerdupe 1.0.0
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.2
		arcanus: Arcanus 1.25
		architectury: Architectury 3.4.9
		armorposer: Armor Poser 1.0.2
		artifality: Artifality 0.5.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		auto_planter: AutoPlanter 18.1-fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autosmeltenchant: AutosmeltEnchant 1.1.0
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.1
		balm-fabric: Balm 2.4.0+0
		basicaiots: Basic AIOTs 1.3.3+1.18.1
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.2.2
		besmirchment: Besmirchment 1.18-5
		better_wandering_trader: Better Wandering Trader 1.8.0
		better_withered_mobs: Better Withered Mobs 1.7.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.3
		betterbeacon: Better Beacons 1.0.7
		betterend: Better End 1.0.0
		betternether: Better Nether 6.0.8
		bewitchment: Bewitchment 1.18-4
		bigbeacons: Big Beacons 1.2.4
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		botania: Botania 1.18.1-427-FABRIC
		bountiful: Bountiful 2.0.1
		cacao: Croptopia's Chocolaterie 0.5
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.2.3+MC1.18-1.18.1
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		chat_plus: Chat+ 2.1.6
		chickensshed: ChickensShed 1.18.1-1.3
		chisel: Chisel Refabricated 1.4.4
		chiselsandbits: Chisels & Bits 1.2.66
		chord: Chord 1.8.0+1.18-fabric
		cleanview: CleanView 1.18.1-v1-fabric
		clickadv: Clickable Advancements Mod 2.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.4
		cmdspy: Command Spy 1.2.3
		columns: Columns 1.2.0
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_google_inject_guice: guice 5.0.1
		com_konghq_unirest-java_standalone: unirest-java 3.13.4
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.0.0-1.18
		companion_bats: Companion Bats 1.18.7
		completeconfig: CompleteConfig 1.3.3
		computercraft: CC: Restitched 1.100.0
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.18+1.18
		connected-doors: Connected Doors 1.1+1.18
		craftingtweaks: Crafting Tweaks 13.0.0
		create: Create mc1.18.1_v0.4b
		creeperoverhaul: Creeper Overhaul 0.2.1
		crimsonnbt: CrimsonNBTTags 1.18.1-Fabric-v1.0.0
		croptopia: Croptopia 1.8.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		customstars: Custom Stars 0.7+1.18
		dankstorage: Dank Storage 1.18.1-3.4
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 9.0.2
		darkwaters: Dark Waters 0.0.9
		dawn: Dawn API 3.2.0
		decorative_blocks: Decorative Blocks 2.0.2
		deepslatecutting: Deepslate Cutting 1.3.0
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		dimores: DimensionalOres 1.0.2
		discordium: Discord Chat Forwarding 1.1.2+1.18.1
		disenchanter: Disenchanter 0.1.4+1.18
		dispenser_configurator: Dispenser Configurator 1.2.1+MC1.18-1.18.1
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.0-beta2
		dml-refabricated-base: DML: Refabricated - Base 0.5.0-beta2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.0-beta2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.0-beta2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.0-beta2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.0-beta2
		doom: Doom Fabric 4.0.2
		draggable-resource-packs: Draggable Resource Packs 2.0.0
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		ducts: Ducts 1.1.5
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easymagic: Easy Magic 3.2.1
		ec-core: Essential Commands Core 1.0.1-mc1.18.1
		eights_economy_p: EightsEconomyP 1.0.1
		eldritch_mobs: Eldritch Mobs 1.10.2
		emerald_tools: Emerald Tools 1.3.33
		emotecraft: Emotecraft 2.1-SNAPSHOT-build.10
		enchant_giver: Enchant Giver 1.1.0
		enchant_the_rainbow: Enchant the Rainbow 1.0.0
		enhanced_quarries: Enhanced Quarries 1.2.0_RC9
		equivalence: Equivalence 1.2.3
		essential_commands: Essential Commands 0.19.0-mc1.18.1
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.2
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.3
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.3
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.2
		expandedstorage: Expanded Storage 7.3.6
		extrasponges: ExtraSponges 1.2.0
		ezpas: Ezpas 2.0.1
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.0+abf02f7665
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricenchantments: Fabric Enchantments 0.6.1
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		fake-player-api: Fake Player API 0.3.0
		fallingtree: FallingTree 3.0.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farmingforblockheads: Farming for Blockheads 9.0.2
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric $version
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireplacelib: Fireplace Lib 6.2.2+1.18
		flight_rings: Flight Rings 1.6.1b
		flytre_lib: FlytreLib 1.6.4
		forge_tags: Forge Tags 1.3
		forgeconfigapiport: Forge Config API Port 3.1.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		fractalportals: FractalPortals 1.2.1
		friendsandfoes: Friends&Foes 1.1.0
		ftbchunks: FTB Chunks 1801.3.3-build.106
		ftblibrary: FTB Library 1801.3.5-build.106
		ftbteams: FTB Teams 1801.2.4-build.46
		geckolib3: Geckolib 3.0.23
		geodes: More Geodes 1.2.0
		giftit: Gift It! 1.5.0+mc1.18-rc3
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.58
		goldenhoppers: Golden Hoppers 1.2.0
		golemancy: Golemancy 1.1.5
		golemsgalore: Golems Galore 1.1.1-1.18
		grass_pass: Grass Bypass 1.1.0
		greater_eye: Greater Eye of Ender 1.3.19
		guild: Guild 0.3.7
		haema: Haema 1.8.2+1.18.1
		hardened-crops: Hardened Crops 1.0
		health_levels: Health Levels 1.0.2
		hologram-api: Hologram API 0.2.1+1.18-pre5
		horseinfo: Horse Info 0.4.1-1.18
		hoverpets: Hover Pets 0.1.1
		hplus: Better Hoppers (Hopper+) 3.0.1
		iceberg: Iceberg 1.0.38
		impaled: Impaled 1.0.1
		impersonate: Impersonate 2.4.0
		indrev: Industrial Revolution 1.13.5-BETA
		interactic: Interactic 0.1.7+1.18
		invview: InvView 1.4.8-1.18+
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		ironchests: Iron Chests for Fabric 1.5.3
		ironfurnaces: Iron Furnaces 3.0.0
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		javax_inject_javax_inject: javax.inject 1
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.6
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.1-build.271
		kyrptconfig: Kyrpt Config 1.2.4-1.18
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.10.0
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.2
		lithium: Lithium 0.7.7
		logprot: Logprot Mod 1.18-1.5
		lootcrates: Modular Loot Crates 2.7.0-1.18.1
		lovely_snails: Lovely Snails 1.0.3+1.18
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magicfungi: Magic Fungi 0.6.2-BETA+1.18.1
		magna: Magna 1.7.0-1.18-pre1
		malusphaethusa: Malus Phaethusa 1.0.2
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mcda: MC Dungeons Armors 1.9.0
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 4.0.1
		megane: megane 6.2.0
		megane-applied-energistics-2: megane-applied-energistics-2 6.2.0+10.0.0-alpha.1
		megane-base: megane-base 6.2.0
		megane-dml-simulacrum: megane-dml-simulacrum 6.2.0+0.5.0-beta2
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-industrial-revolution: megane-industrial-revolution 6.2.0+1.13.1-BETA
		megane-kibe: megane-kibe 6.2.0+1.9.4-BETA-1.18
		megane-lib-block-attributes: megane-lib-block-attributes 6.2.0+0.10.0
		megane-modern-industrialization: megane-modern-industrialization 6.2.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.2.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.2.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.2.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		megane-wireless-networks: megane-wireless-networks 6.2.0+1.4.0
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.1.6
		milk_plus: Milk+ 2.0.1
		minecraft: Minecraft 1.18.1
		mining_dims: Mining Dimensions 1.2.38
		miningcooldownfix: Mining Cooldown Fix 1.18.1-1.0.0
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.20
		modern_industrialization: Modern Industrialization 1.0.4
		more-axolotls: More Axolotls 1.0.2
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mosslayers: Moss Layers 1.0.1
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		multibeds: MultiBeds 1.2.0
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		multisleep: Multiplayer Sleep 1.2
		myron: Myron 1.6.2+1.18.1
		nameplate: Nameplate 1.0.2
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		nears: Nears 1.1.2
		net_dv8tion_jda: JDA 5.0.0-alpha.1
		net_sf_trove4j_trove4j: trove4j 3.0.3
		netherportalfix: NetherPortalFix 9.0.0
		neutral_animals: Neutral Animals 1.1.1
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.10
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		noenchantcap: No Enchant Cap 1.18.1-fabric-2.1.1
		noooooo: noooooo 1.0.0
		not-that-cc: Crafty Crashes 1.0
		octo-economy-api: Octo Economy API 1.0.0
		omega-config: OmegaConfig 1.2.2-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		openloader: OpenLoader 11.0.3
		ore_tree: Ore Tree 0.2.0
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_jetbrains_annotations: annotations 16.0.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		ottercraft: Ottercraft 1.1.10
		owo: oÏ‰o 0.3.14+1.18
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paradoxconfig: Paradox Config 0.5.1-beta
		patchouli: Patchouli 1.18.1-64-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		physicsmod: Physics Mod 2.6.4
		pigsteel: Pigsteel Mod 1.7.0
		pitch-dark: Pitch Dark 2.0.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		platforms: Platforms 1.2.0
		player-data-api: Player Data API 0.1.0+1.18
		playerabilitylib: Pal 1.4.0
		polymer: Polymer 0.2.0-beta.15+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.15+1.18.1
		polymorph: Polymorph 0.0.18-1.18.1
		proper-mobcap-modifier: Proper Mobcap Modifier 3.1
		pswg: Galaxies: Parzi's Star Wars Mod 0.0.54+1.18.1
		pugh_lib: Pugh Lib 1.2.13
		pugh_tools: Pugh Tools 1.1.16
		puzzleslib: Puzzles Lib 3.1.3
		quarrymod: Industial Quarry Mod 0.5.3
		quarryplus: QuarryPlus 18.1.0
		randore: Rand'Ore 1.4.1-1.18
		ratsmischief: Rat's Mischief 1.3.4
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reapingmod: Reaping Mod 1.6.2
		reborncore: Reborn Core 5.1.0-beta.5
		recipecache: recipecache 0.2.1-1.17.1
		redbits: Red Bits 1.11.0
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		reinfbarrel: Reinforced Barrels 1.0.5+1.18
		reinfcore: Reinforced Core 1.1.2+1.18
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		resclone: Resclone 1.8.0
		resourcemelons: Resource Melons 2.2.3
		resourcemelonstechreborn: Resource Melons - Tech Reborn 1.0.0
		resourceoverhaul: Resource Overhaul 2.3
		retail: Retail 0.3.5
		rhino: Rhino 1800.1.7-build.92
		right-click-harvest: Right-Click-Harvest 1.1.0
		roughlyenoughitems: Roughly Enough Items 7.1.357
		roughlysearchable: Roughly Searchable 2.3.0+1.18.1
		rpgdifficulty: Rpg Difficulty 1.0.8
		satako: Satako 0.1.0-1.18.1
		sculk_worm: Sculk Worm 0.1.3
		searchlight: Searchlight 1.1.5
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shetiphiancore: ShetiPhianCore 1.2.0
		shoppy: Shoppy 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shwfox: Shadew's Foxes 1.2+fabric
		sihywtcamd: sihywtcamd 1.5.2+1.18
		simple_backpack: SimpleBackpack 1.2.28
		simple_cobblestone_generator: Simple cobblestone generator 1.1.7
		simplyplatinum: Simply Platinum 4.2
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		slotlink: slotlink 4.0.4
		smart_pipes: Smart Pipes 3.0.0-1.18.1
		smoothboot: Smooth Boot 1.18-1.7.0
		soaringstructures2: Soaring Structures 2 1.18 - 2.1
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.3
		spatialharvesters: Spatial Harvesters 0.11.12d
		spectrum: Spectrum 1.2.2-1.18.1-midgame3
		starlight: Starlight 1.0.0+fabric.0ce1826
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		statues: Statues 1.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.1
		storagecabinet: Storage Cabinet 1.4.2
		structurized: Structurized 1.4.0+1.18
		styledplayerlist: Styled Player List 2.1.3+1.18
		talking-villagers: Talking Villagers 1.1.3
		team_reborn_energy: Energy 2.1.0
		techreborn: Tech Reborn 5.1.0-beta.5
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.8
		the_bumblezone: The Bumblezone - Fabric 4.1.1+1.18.1
		things: Things 0.2.10+1.18
		thonkutil: ThonkUtil 2.6.0+1.18
		thonkutil-base: ThonkUtil Base 1.4.0+6a7a08aec8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.0+a46c8f89c8
		thonkutil-customization: ThonkUtil Customization (v1) 1.0.1+6a7a08aec8
		thonkutil-legacy: ThonkUtil Legacy 1.0.7+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.5+6a7a08aec8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.5+6a7a08aec8
		timeoutout: TimeOut Out 1.0.0+1.18
		tinyskeletons: Tiny Skeletons 3.1.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		tooltiprareness: Tooltip Rareness 1.0.3
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		trade: Trade 1.2.2
		tradingpost: Trading Post 3.1.2
		transportables: Transportables 1.1
		trapexpansion: Trap Expansion 1.3.3
		trashslot: TrashSlot 11.0.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed: Tweed API 3.0.0-beta.22
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		twigs: Twigs 1.1.2
		twm: The Wild Mod 0.4
		unforgivingvoid: Unforgiving Void 3.1.1+1.18
		universal-graves: Universal Graves 2.0.0-beta.3+1.18
		unvotedandshelved: Unvoted & Shelved 1.0.4
		urns: Urns 1.0.1
		valley: ValleyCraft 2.1
		vanilla_degus: Vanilla Degus 1.3.0
		villager-hats: Villager Hats Mod 1.2.1
		villager_see_villager_do: Villager See, Villager Do 1.1.3+MC1.18-1.18.1
		visualoverhaul: VisualOverhaul 4.0.0
		visualworkbench: Visual Workbench 3.1.0
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		wands: Building Wands 2.3.1
		waystones: Waystones 2.4.1
		whereisit: Where Is It 1.14.6
		wilderworld: WilderWorld 1.0.0
		wireless_redstone: Wireless Redstone 2.0.0
		wirelessnetworks: Wireless Networks 1.4.1
		wthit: wthit 4.4.1
		xlpackets: XLPackets 2.1-1.17.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
		zihlaunchpads: ZIHLaunchpads 1.2.0
```

**Comment by frikinjay** [comment] 2022-01-09 15:30
Took a closer look at logs looks like mixin conflict between artifality and sihytcamd leading to removal of wither skeleton so the loot couldnt be accessed. Youre free to close it on your end if you dont find anything else, this seems like an issue on the part of one of the mods mentioned up there and i'll report it there.

**Comment by Luligabi1** [comment] 2022-01-09 21:04
👍🏼 couldn't reproduce on our side, so I'm closing this. Feel free to make a new issue if any issues arise.

**Closed by Luligabi1** 2022-01-09 21:04 UTC
