### ISSUE TITLE
crash on itcking entity

### ISSUE THREAD

**Issue by TheNimbleNinja** [NathanPB/DeepMobLearning-Refabricated#44] opened 2021-06-13 23:33 UTC
https://gist.githubusercontent.com/natanfudge/a262394f421ef3d4fc08ea336bbab3de/raw/298d5bee93aee38055db376e2591fbfdaf269d89/crash.txt

**Comment by NathanPB** [comment] 2021-06-14 00:07
Closed as a dupe of #43, fixed in 0.4.0-beta2

**Closed by NathanPB** 2021-06-14 00:07 UTC
